# Generated by Django 4.1 on 2022-11-05 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=70)),
                ('Department_Info', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='EmployModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('Employ_Age', models.IntegerField()),
                ('Employ_Photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('email', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officeapp.departmentmodel')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_Name', models.CharField(max_length=100)),
                ('Std_Address', models.CharField(max_length=200)),
                ('Std_Age', models.IntegerField()),
                ('Student_Gender', models.CharField(max_length=10)),
                ('Join_Date', models.DateField(auto_now_add=True)),
                ('Student_Image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officeapp.departmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('tdesc', models.CharField(max_length=200)),
                ('sdate', models.CharField(max_length=200)),
                ('edate', models.CharField(max_length=200)),
                ('employ_file', models.FileField(blank=True, null=True, upload_to='emp_files/')),
                ('Employ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officeapp.employmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployLeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.CharField(max_length=200)),
                ('edate', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('rleave', models.CharField(max_length=200)),
                ('Employ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officeapp.employmodel')),
            ],
        ),
    ]
