# Generated by Django 4.1 on 2022-11-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployLeaveModel',
        ),
    ]
