# Generated by Django 4.1 on 2022-11-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0002_delete_employleavemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployLeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('leave_status', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('admin_comments', models.CharField(max_length=200)),
                ('Employ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officeapp.employmodel')),
            ],
        ),
    ]
