# Generated by Django 4.1 on 2022-11-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0003_employleavemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employleavemodel',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employleavemodel',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
