# Generated by Django 4.1 on 2022-11-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0004_alter_employleavemodel_from_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
