# Generated by Django 4.1 on 2022-12-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0005_delete_studentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmodel',
            name='password',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
