# Generated by Django 4.1 on 2022-12-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0006_employmodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmodel',
            name='password',
        ),
    ]
